---
name: kbruch
version: 17.08.1
summary: Practice exercises with fractions
description: |-
    KBruch is a small program to practice calculating with fractions and percentages. Different exercises are provided for this purpose and you can use the learning mode to practice with fractions. The program checks the user's input and gives feedback.

    Features:

    - Arithmetic exercise - in this exercise you have to solve a given fraction task. You have to enter the numerator and the denominator. This is the main exercise.
    - Comparison exercise - in this exercise you have to compare the size of 2 given fractions, using the symbols \>, \< or =.
    - Conversion exercise - in this exercise you have to convert a given number into a fraction.
    - Factorization exercise - in this exercise you have to factorize a given number into its prime factors.
    - Percentage exercise - in this exercise you have to calculate percentages.
confinement: strict
grade: stable
apps:
    kbruch:
        command: kf5-launch kbruch
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kbruch
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kbruch:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kbruch-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
